name: sanpo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.8
  location: ^8.0.0
  permission_handler: ^11.4.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.0.0
  flutter_compass: ^0.8.0
  background_locator_2: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true